theme: jekyll-theme-cayman
title: "Ladino - Judeo-Spanish"
description: "Ladino, the language of the Sepharadic Jews"
show_downloads: false
github:
   is_project_page: false
#plugins:
#  - jekyll-sitemap
